services:
  elasticsearch:
    image: elasticsearch:7.17.26
    container_name: elasticsearch
    ports:
      - 9200:9200
    environment:
      discovery.type: ${DISCOVERY_TYPE}
      xpack.security.enabled: ${XPACK_SECURITY_ENABLED}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      ES_JAVA_OPTS: ${ES_JAVA_OPTS}
    networks:
      - default
      - proxy
  kibana:
    image: kibana:7.17.26
    container_name: kibana
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    networks:
      - proxy
      - default
networks:
  proxy:
    external: true
