version: '3.8'
services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    privileged: true
    networks:
      - proxy
    #ports:
    # - '9000:9000'
    volumes:
      - './data:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
    restart: unless-stopped
networks:
  proxy:
    external: true
